services:
  backend-base:
    build:
      dockerfile: ./docker/Dockerfile_backend
      context: .
      args:
      - DB_USER=${DB_USER:-eventUser}
      - DB_PASSWORD=${DB_PASSWORD:-Hug3SwamplandRubber}
      - DB_IP=db-prod
      - DB_PORT=5432
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}


    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://*:1600

    ports:
      - 1600:1600
    networks:
      - eventManager


  db-base:
    image: postgres:18-trixie
    environment:
        POSTGRES_USER: ${DB_USER:-eventUser}
        POSTGRES_PASSWORD: ${DB_PASSWORD:-Hug3SwamplandRubber}
        POSTGRES_DB: EventManagerDb
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d EventManagerDb" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - eventManager

  frontend-base:
    build:
      dockerfile: ./docker/Dockerfile_frontend
      context: .
      args:
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - 1601:80
    restart: unless-stopped

