FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 1600


FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG DB_USER
ARG DB_PASSWORD
ARG DB_IP
ARG DB_PORT
ARG BUILD_CONFIGURATION=Release
ARG BACKEND_URL
ARG FRONTEND_URL
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_IP=${DB_IP}
ENV DB_PORT=${DB_PORT}
ENV BACKEND_URL=${BACKEND_URL}
ENV FRONTEND_URL=${FRONTEND_URL}

RUN apt-get update && apt-get install -y gettext-base && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY ["./EventManager", "./EventManager"]
COPY ["./EventManager.Shared", "./EventManager.Shared"]
RUN dotnet restore "./EventManager/EventManager.csproj"
RUN envsubst < ./ElevatorContentManager/appsettings.deploy.json > ./ElevatorContentManager/appsettings.json
RUN dotnet build "./EventManager/EventManager.csproj" -c "$BUILD_CONFIGURATION" -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./EventManager/EventManager.csproj" -c "$BUILD_CONFIGURATION" -o /app/publish /p:UseAppHost=false


FROM base AS final

USER $APP_UID

WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "ElevatorContentManager.dll"]