FROM node:22-alpine as build
WORKDIR /app
COPY package*.json ./
COPY ./frontend .
RUN npm install
ARG CONFIG
ARG BACKEND_URL
ENV BACKEND_URL=${BACKEND_URL}

RUN sed -i "s|http://localhost:1600/api|${BACKEND_URL}/api|g" /app/src/environments/environment.ts

RUN npm run build -- --configuration=${CONFIG}



FROM nginx:alpine
COPY ./configs/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]