# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

RUN apt-get update && \
	apt-get install -y --no-install-recommends dos2unix gettext-base uuid-runtime && \
	rm -rf /var/lib/apt/lists/*

ARG BACKEND_URL
ARG FRONTEND_URL
ENV FRONTEND_URL=${FRONTEND_URL}
ENV BACKEND_URL=${BACKEND_URL}

ARG BUILD_CONFIGURATION=Release

WORKDIR /src
COPY ["./ElevatorContentManager.Shared", "./ElevatorContentManager.Shared"]
COPY ["./ElevatorContentManager.Client", "./ElevatorContentManager.Client"]
RUN  dotnet restore "./ElevatorContentManager.Client/ElevatorContentManager.Client.csproj" && \
	envsubst < ./ElevatorContentManager.Client/wwwroot/appsettings.deploy.json > ./ElevatorContentManager.Client/wwwroot/appsettings.json && \
	dotnet build "./ElevatorContentManager.Client/ElevatorContentManager.Client.csproj" -c "$BUILD_CONFIGURATION" -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./ElevatorContentManager.Client/ElevatorContentManager.Client.csproj" -c "$BUILD_CONFIGURATION" -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish . 

FROM nginx:1.28.0-alpine
COPY ./ElevatorContentManager.Client/nginx.conf /etc/nginx/nginx.conf
COPY --from=publish /app/publish/wwwroot /usr/share/nginx/html/